spring.application.name=stronglab-backend

server.port=${PORT:8080}

# Автоматически собираем JDBC URL из стандартной переменной DATABASE_URL хостинга
spring.datasource.url=jdbc:${DATABASE_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Настройки Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#server.port=8081
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/StrongLabDB
#spring.datasource.username=postgres
#spring.datasource.password=1234
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#xKUcNttWXMNNfVhCUkLRLKjcnAgmeNlz
#jdbc:postgresql://postgresql.railway.internal:5432/railway
#